"""инициализация

Revision ID: c1cff38d1055
Revises: 
Create Date: 2025-11-10 22:11:54.568640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cff38d1055'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', name='statusaboutuscontent'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('create_order',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('to_country', sa.String(), nullable=True),
    sa.Column('count_people', sa.String(), nullable=True),
    sa.Column('count_days', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('connection', sa.String(), nullable=True),
    sa.Column('is_created_order', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_send_order', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('mailing_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('start_mailing',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='roleenum'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber')
    op.drop_table('user')
    op.drop_table('start_mailing')
    op.drop_table('mailing_content')
    op.drop_table('create_order')
    op.drop_table('about_us')
    # ### end Alembic commands ###
