"""добавил таблицу mailing_content

Revision ID: 51a13ce19da4
Revises: d24dfd01daaf
Create Date: 2025-06-27 10:18:01.074756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a13ce19da4'
down_revision: Union[str, None] = 'd24dfd01daaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'photo', name='contenttypeenum'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('photo', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailing_content')
    # ### end Alembic commands ###
