"""изменил таблицу mailing_content

Revision ID: db0b62088d69
Revises: 51a13ce19da4
Create Date: 2025-06-27 10:51:28.069866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db0b62088d69'
down_revision: Union[str, None] = '51a13ce19da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailing_content', sa.Column('content', sa.JSON(), nullable=True))
    op.drop_column('mailing_content', 'photo')
    op.drop_column('mailing_content', 'text')
    op.drop_column('mailing_content', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailing_content', sa.Column('content_type', postgresql.ENUM('text', 'photo', name='contenttypeenum'), autoincrement=False, nullable=False))
    op.add_column('mailing_content', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mailing_content', sa.Column('photo', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('mailing_content', 'content')
    # ### end Alembic commands ###
