name: Deploy to VPS
# событие экшена
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
jobs: 
  test:
    services:
      db_testing:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
          # APP_PORT: 3008
          # POSTGRES_PORT: 5433 
        ports:
          - 5433:5432

    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v4

    # - name: Login to Docker Hub
    #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # - name: create .env file
    #   run: |
    #     cat > .env << EOF
    #     APP_PORT=3008
    #     POSTGRES_USER=test
    #     POSTGRES_PASSWORD=test
    #     POSTGRES_DB=test
    #     POSTGRES_PORT=5433
    #     EOF

    # - name: Run docker compose
    #   uses: hoverkraft-tech/compose-action@3846bcd61da338e9eaaf83e7ed0234a12b099b72 # v2.4.1
    #   env:
    #     POSTGRES_USER: test
    #     POSTGRES_PASSWORD: test
    #     POSTGRES_DB: test
    #     APP_PORT: 3008
    #     POSTGRES_PORT: 5433 
    #   with:
    #       compose-file: "./docker-compose.yml"
    #       services: app
    #       # up-flags: --build db_testing

    - name: Install dependencies
      
      run: |
        pip install -r requirements.txt

    - name: Test app
      # env:
        # POSTGRES_PORT: 5432
      run: |
        python -m pytest -s
      

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # авторизация в docker hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Deploy to VPS and build
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /root/github/mailing_bot && \
            git pull origin main && \
            docker-compose down && \
            docker-compose up -d --build
          " 
            
      - name: Waiting up containers
        run: sleep 5

      - name: Make migrate
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
           cd /root/github/mailing_bot && docker-compose exec -T app make migrate
          "

  # test:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #     - name: Setup SSH
  #       uses: webfactory/ssh-agent@v0.9.0
  #       with:
  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  #     - name: Test app
  #       run: |
  #         ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
  #           cd /root/github/mailing_bot && docker-compose exec -T app make test
  #         "
