name: Deploy to VPS
# событие экшена
# on: workflow_dispatch -ручное
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # авторизация в docker hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Deploy to VPS and build
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /root/github/mailing_bot && \
            git pull origin main && \
            docker-compose down && \
            docker-compose up -d --build
          " 
            
      - name: Waiting up containers
        run: sleep 5

      - name: Make migrate
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker-compose exec app make migrate
          "

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test app
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker-compose exec app make test
          "
