name: Deploy to VPS
# событие экшена
# on: workflow_dispatch -ручное
on: 
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
jobs:
  # название задачи
  # test:
  #   # на какой системе запускается ranner
  #   runs-on: ubuntu-latest
  #   steps:
  #     # название шага
  #     - name: Get repository code
  #     # названия плагина для копирования проекта для последующего выполнения
  #       uses: actions/checkout@v4
      
  #     # кэширование зависимостей чтобы в след задаче не повторять установку, а взять из кэша
  #     - name: Cache dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.cache/pip
  #         key: pip-${{ hashFiles('**/requirements.txt') }}

  #     - name: Install dependencies
  #       run: pip install -r requirements.txt 

  #     - name: Test app
  #       run: make test

    # название задачи
    deploy:
      runs-on: ubuntu-latest
      # завистимость от шага deploy
      needs: test
      steps:
        - name: Get repository code
          uses: actions/checkout@v4
        
        - name: Setup SSH
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        # авторизация в docker hub
        - name: Login to Docker Hub
          run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

        - name: Deploy to VPS
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
              cd /root/github/mailing_bot && \
              git pull origin main && \
              docker-compose down && \
              docker-compose up -d --build 
              
        - name: Waiting up containers
          run: sleep 5

        - name: Test app
          run: sudo docker-compose exec app pytest -s

  
